- name: Install ngnix
  host: web
  become: yes #becoming root user
  task:
    - name: Install nginx
      ansible.builtin.dnf:
        name: nginx
        state: latest
    - name: start service
      ansible.builtin.service:
        name: nginx
        state: started
